# Generated by Django 4.2.6 on 2023-11-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adresse',
            field=models.TextField(default='Votre_adresse'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='civilite',
            field=models.CharField(default='Monsieur', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nom',
            field=models.CharField(default='Votre Nom', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(default=31000, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prenom',
            field=models.CharField(default='Votre Prenom', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selected_pays',
            field=models.CharField(default='Pays', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ville',
            field=models.CharField(default='Ville', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_de_naissance',
            field=models.DateField(blank=True, default='01/01/0101', null=True),
        ),
    ]
