# Generated by Django 4.2.6 on 2023-11-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_adresse_userprofile_civilite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
