# Generated by Django 4.2.7 on 2023-11-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_product_category_remove_product_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(default='00000', max_length=20),
        ),
    ]
