# Generated by Django 4.2.7 on 2023-11-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_pays_remove_userprofile_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='selected_pays',
            field=models.CharField(default='Pays', max_length=255),
        ),
        migrations.DeleteModel(
            name='Pays',
        ),
    ]
