# Generated by Django 4.2.7 on 2023-11-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_username_alter_userprofile_selected_pays_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='selected_pays',
            new_name='selectedPays',
        ),
    ]
