# Generated by Django 4.2.7 on 2023-11-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_selected_pays_userprofile_selectedpays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='selectedPays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.pays'),
        ),
    ]
