# Generated by Django 4.2.7 on 2023-11-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_pays_alter_userprofile_selectedpays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='selectedPays',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Pays',
        ),
    ]
