# Generated by Django 4.2.7 on 2023-11-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_userprofile_email_remove_userprofile_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nom',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prenom',
            field=models.CharField(default='', max_length=20),
        ),
    ]
