# Generated by Django 4.2.7 on 2023-11-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_userprofile_selectedpays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='prenom',
        ),
    ]
