# Generated by Django 4.2.7 on 2023-11-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_userprofile_email_remove_userprofile_nom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='selectedPays',
            new_name='selected_pays',
        ),
    ]
