# Generated by Django 4.2.7 on 2023-11-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_selectedpays_userprofile_selected_pays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='selected_pays',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selectedPays',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Pays',
        ),
    ]
