# Generated by Django 4.2.7 on 2023-11-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_userprofile_selected_pays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='selectedPays',
            field=models.CharField(default='Pays', max_length=255),
        ),
    ]
