# Generated by Django 4.2.6 on 2023-10-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='en_promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
